
== Password Implementierung

Eine zentrale Aufgabe ist es Passwörter geheim zu halten. Sei
es in Log Dateien oder auf dem Bildschirm. Dabei geht es nicht 
immer um eine harte Verschlüsselung, sondern auch darum, dass
Passwörter nicht einfach beim 'vorbei gehen' aufgeschnappt
werden können. Also eine Verschleierung von Daten.

Hierbei hilft das `MPassword` Tool. Es nutzt intern eine 
Implementierung von `IPassword`. Der Standart `DefaultPassword`
reicht für die meisten Anwendungen aus, kann aber auch als Bean 
bereitgestellt werden bzw. erweitert werden.

Die Implementierung stellt Standarts wie ROT13 bzw. ROT13AND5
(erweitert Rot13 um die Rotation von Digits). 

IMPORTANT: Die Rot13 Verschleierung ist keine sichere Verschlüsselung
sondern dient nur der Unkentlichmachung auf dem Bildschirm. Jeder kann
technisch ohne Aufwand das Passwort rekonstruieren.

Außerdem werden Hashing-Algorythmen unterstützt. Standart ist
eine separate Implementierung von MD5. Es wird in `core` explizit
keine Abhängigkeit zu `javax.security` hergestellt um Anwendungen
schlanker halten zu können.

Es können weitere Passwort-Encryption-Algorithmen bereitgestellt
werden indem Beans mit dem Interface `IPasswordEncoder` registriert
werden. Der Name der Bean dient als Name des Algorithmus.

Wird beim verschlüsseln kein Algorithmus angegeben wird die 
Konfiguration aus `org_summerclouds_core_tools_MPassword.default`
genutzt. Ohne Konfiguration `Rot13And5`.

Verschlüsselte Passwörter werden im ersten Zeichen mit einem 
Hochkomme gekennzeichnet, danach der Algorithmus gefolgt mit einem
Dollar als Trennzeichen zum verschlüsselten Passwort.

In dieser Bibliothek werden Passwörter an vielen Stellen unkenntlich 
gemacht und wieder entschlüsselt.

Beispiel:

----

String obfuscated = MPassword.encode(plainPassword);
String plain = MPassword.decode(obfuscated);

String md5 = MPassword.encode(MPassword.MD5, plainPassword);
boolean valid = MPassword.validate(plain, md5);

----

== Keychain Implementierung

Die Keychain ist eine zentrale Ablage für geheime Daten. Die Daten
werden möglichst verschlüsselt oder remote abgelegt. Dafür können
der Keychain mehrere Data-Source hinzugefügt werden, die je 
nach Implementierung Daten verschlüsseln.

In `core` ist nur eine Dummy Keychain hinetrlegt, die Daten nur 
im Speicher hält. Wird eine echte Keychain benötigt, ist diese
im Packet `crypt` enthalten, muss hier aber aktiviert werden.

In der keychain können z.B. Passwörter oder Public / Private Keys
abgelegt werden die für die Abarbeitung relevant sind. Bzw.
Read-Only Sources in Cloud Umgebungen


