//@manual

== Log Erweiterung

Die Log-Erweiterung ist eine Fassade und vereinfacht das Loggen mit dem Standard Logger.
Die Log-Engine kann gewechselt werden sollte aber immer den Spring logger bzw. SlfJ
nutzen. Eine alternative ist die direkte Ausgabe auf die Konsole.

Die Vereinfachung liegt vor allem beim Aufruf und der Ausgabe der Daten. Der Aufruf kann durch
shortcut Funktionen 

* f() für fatal(), 
* e() für error(), 
* w() für warn(), 
* i() für info(), 
* d() für debug() und 
* t() für trace() 

verkürzt werden. Alle Funktionen können eine Nachricht (msg) und
weitere Parameter aufnehmen. Die Parameter können in der Nachricht durch '{nr}' referenziert
werden.

NOTE: Zur Ausgabe siehe auch Exceptions.

Ist das Log-Level nicht erreicht werden die parameter nicht zu einer Log-Nachricht aggrigiert 
und somit keine Rechenzeit verbraucht. Deshalb empfiehlt es sich in den Parametern ganze
Objekte zu übergeben und diese vorher explizit nicht in Strings umzuwandeln.

Sollen Objekte durch einen besonderen Source Code in einen String umgewandelt werden können
ParameterMapper hinterlegt werden die anstelle von toString() genutzt werden um aus einem
Parameter einen repräsentativen Text zu erstellen.

Wird in einer Klasse von MLog abgeleitet kann die Tool-Funktion log() genutzt werden um
zu loggen. Der Logger wird erst beim ersten Aufruf erstellt. Durch diese emfolhene
Vorgehen kann ebenfalls Rechenzeit gespart bzw. verteilt werden.

=== Plain Log

In manchen Situationen ist es nicht möglich einen voll ausgerollten
Log-Service zu nutzen. In diesem Fall kann der `plain log` genutzt
werden. Es werden alle Einträge direkt in die Konsole ausgegeben.

=== Log Factory

Eine Log-Factory stellt eine Implementierung einer echten Log
Factory dar. Die Factory erstellt für jedes benötigte LogFacade 
eine Fasade für den eigentlichen Logger bereit.

=== Konfiguration

Prefix:: org.summercloud.core.log.Log

* `maxMsgSize` : int - Set maximal message size or set to 0 to disable, 
default is 10000
* `logTraceId` : bool : Set true to add trace id in front of the log message,
default is true

=== ParameterEntryMapper Beans

Um die Objekt-Anzeige anzupassen können ParameterEntryMapper als
Beans hinterlegt werden. Der Bean name muss dem Namen der
Klasse bzw. Interfaces entsprechen, das durch den Mapper
in einen String umgesetzt wird.

Beispiel:

[java]
----
@Bean("java.lang.Date")
public ParameterEntryMapper dateMapper() {
  return new ParameterEntryMapper() {
    Object map(Object in) {
      if (in instanceof Date)
        return MDate.toIsoDate((Date)in);
      return in;
    }
  }
}
----

=== Weitere Log Appender

`Core` sucht alle Beans mit dem Typ `Appender` und
hängt diese als Log-Appender an das Log-System.

Beispiel:

[java]
----

@Bean
public Appender extends UnsynchronizedAppenderBase<ILoggingEvent> {

  @Override
  protected void append(ILoggingEvent event) {
    ...
  }
}

----


