
== Cmd Framework

Warum einen Cmd Framework?

Der Framework gibt die Möglichkeit die Anwendung
mit einfach von aussen ausführbaren Befehlen zu
erweitern. Der Framework ist hilfreich für den
Support und den Betrieb der Anwendung.

Commands werden in einem eigenen Prozess ausgeführt
und die Ausgabe auf stdio wird in einem InputStream
bzw. bei der Operation ein StreamResult zurückggegeben. 

Der Aufrufende muss mti diesem InputStream umgehen
können.

Um ein Command zu definieren können Variablen mit
den Annotationen `@CmdArgument` oder `@CmdOption`
markiert werden. Die Daten werden beim Aufruf
mit den mitgelieferten Werten gefüllt.

InputStream und OutputStream können alternativ
als parameter übergeben werden. Bitte die
beiden Konstanten benutzen. In diesem Fall ist
der Stream in der Rückgabe `null`.

Beispiel:

----

MNode config = new MNode();
config.put(CmdOperation.PARAMETER_OUTPUT_STREAM, new FileOutputStream("output.log"));

OperationResult res = manager.execute(path, config);

----

=== Konfiguration

Um alle Log-Ausgaben in die CMD ausgabe umzuleiten:

org.summerclouds.ThreadConsoleLogAppender.enabled=true

=== Protokoll

Bei der Ausführung wird die Ausgabe des Kommandos 
direkt zum ausführenden Client gesendet (Stream).
Das Zeichen '0' markiert im Protokoll einen Token
der zum transport von besoneren Datensätzen
genutzt wird. Das Folgezeichen definiert welche
Daten gesendet werden.

* '\0' (0) - Es handelt sich um ein einzelnes '\0' Zeichen
* '\n' (13) - Das Ergebnis wird in Folge gesendet, 
beendet mit einem weiteren '\0' Zeichen
* 'n' (110) - Das Ergebnis ist `null` (ersetzt die Ausgabe '\n')
* 'e' (101) - Das Ergebnis ist eine Exception, gefolgt von der 
Exception, beendet mit einem `\0` Zeichen (ersetzt die Ausgabe '\n')
* 'f' (102) - Es folgt ein Hex-Datensatz/Dateiinhalt, 
zuerst der Dateiname, beendet mit einem '\0' Zeichen,
danach der Datenstream in HEX beendet mit '\0'.

